version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000

  redis:
    image: redis
    #volumes:
    #  - redis_volume:/data
    ports:
      - 6379:6379

  celery:
    build: .
    command: celery -A _settings worker -l info

  celery-beat:
    build: .
    command: celery -A _settings beat -l info
    volumes:
        - .:/code
    depends_on:
        - redis

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432

volumes:
    postgres_volume:
    #redis_volume:

