# Generated by Django 5.1.1 on 2024-10-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_info_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IpAddress',
        ),
    ]
