# Generated by Django 5.1.1 on 2024-11-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_history', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_first_name',
            field=models.CharField(max_length=50),
        ),
    ]
