# Generated by Django 5.1.1 on 2024-11-04 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_history', '0003_alter_users_user_first_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_first_name',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='users',
            name='login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='user_last_name',
            field=models.CharField(max_length=50),
        ),
    ]
