# Generated by Django 4.2.16 on 2024-11-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_history', '0004_rename_user_first_name_users_user_name_users_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_last_name',
        ),
    ]
